;*/
;* @Date:		5/27/21
;* @Author:		Szyfr
;*/


extrn 'WindowShouldClose' as WindowShouldClose
extrn 'IsKeyDown' as IsKeyDown
extrn 'BeginDrawing' as BeginDrawing
extrn 'ClearBackground' as ClearBackground
extrn 'BeginMode2D' as BeginMode2D
extrn 'DrawRectangle' as DrawRectangle
extrn 'DrawTexture' as DrawTexture
extrn 'EndMode2D' as EndMode2D
extrn 'EndDrawing' as EndDrawing
extrn 'DrawTextureRec' as DrawTextureRec
extrn 'InitWindow' as InitWindow
extrn 'SetTargetFPS' as SetTargetFPS
extrn 'MemAlloc' as MemAlloc
extrn 'LoadImage' as LoadImageRL
extrn 'UnloadImage' as UnloadImage
extrn 'LoadTextureFromImage' as LoadTextureFromImage
extrn 'ImageResizeNN' as ImageResizeNN
extrn 'SetWindowIcon' as SetWindowIcon
extrn 'LoadFileData' as LoadFileData
extrn 'UnloadFileData' as UnloadFileData
extrn 'MemFree' as MemFree
extrn 'CloseWindow' as CloseWindowRL
extrn 'IsMouseButtonDown' as IsMouseButtonDown
